"""
Export Controller — generates downloadable PDF reports
for meeting transcripts and analysis summaries.
Uses ReportLab for PDF generation.
"""

import io
import os
from datetime import datetime, timezone
from flask import current_app, g, send_file, jsonify
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
import logging

from models.models import MeetingModel, TranscriptModel, AnalysisModel
from middleware.auth_middleware import verify_meeting_ownership

logger = logging.getLogger(__name__)

# ── Brand colors ───────────────────────────────────────────────────────────────
BRAND_BLUE  = colors.HexColor("#2563EB")
BRAND_DARK  = colors.HexColor("#1E293B")
ACCENT_GRAY = colors.HexColor("#64748B")
LIGHT_GRAY  = colors.HexColor("#F1F5F9")
POS_GREEN   = colors.HexColor("#16A34A")
NEG_RED     = colors.HexColor("#DC2626")
NEU_GRAY    = colors.HexColor("#6B7280")


def _build_styles():
    """Build a custom style sheet for the PDF."""
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title", parent=base["Title"],
            fontSize=22, textColor=BRAND_DARK,
            spaceAfter=6, fontName="Helvetica-Bold",
        ),
        "subtitle": ParagraphStyle(
            "subtitle", parent=base["Normal"],
            fontSize=11, textColor=ACCENT_GRAY,
            spaceAfter=20,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"],
            fontSize=14, textColor=BRAND_BLUE,
            spaceBefore=16, spaceAfter=8, fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontSize=10, textColor=BRAND_DARK,
            leading=16, spaceAfter=6,
        ),
        "speaker": ParagraphStyle(
            "speaker", parent=base["Normal"],
            fontSize=9, textColor=BRAND_BLUE,
            fontName="Helvetica-Bold", spaceAfter=2,
        ),
        "segment": ParagraphStyle(
            "segment", parent=base["Normal"],
            fontSize=10, textColor=BRAND_DARK,
            leading=14, leftIndent=12, spaceAfter=8,
        ),
        "bullet": ParagraphStyle(
            "bullet", parent=base["Normal"],
            fontSize=10, textColor=BRAND_DARK,
            leading=14, leftIndent=18, spaceAfter=4,
        ),
        "tag": ParagraphStyle(
            "tag", parent=base["Normal"],
            fontSize=9, textColor=ACCENT_GRAY, spaceAfter=4,
        ),
        "footer": ParagraphStyle(
            "footer", parent=base["Normal"],
            fontSize=8, textColor=ACCENT_GRAY,
            alignment=TA_CENTER,
        ),
    }
    return styles


def _sentiment_color(label: str):
    return {
        "positive": POS_GREEN,
        "negative": NEG_RED,
        "neutral":  NEU_GRAY,
    }.get((label or "").lower(), NEU_GRAY)


def _fmt_duration(seconds: int) -> str:
    if not seconds:
        return "Unknown"
    h, rem = divmod(seconds, 3600)
    m, s   = divmod(rem, 60)
    return f"{h}h {m}m {s}s" if h else f"{m}m {s}s"


def _fmt_time(timestamp) -> str:
    if not timestamp:
        return ""
    if isinstance(timestamp, datetime):
        return timestamp.strftime("%B %d, %Y at %H:%M UTC")
    return str(timestamp)


# ══════════════════════════════════════════════════════════════════════════════
# FULL REPORT (transcript + analysis)
# ══════════════════════════════════════════════════════════════════════════════

def export_meeting_pdf(meeting_id: str):
    """
    GET /api/export/<meeting_id>/pdf
    Generates and streams a full PDF report.
    """
    if not verify_meeting_ownership(meeting_id):
        return jsonify({"error": "Not found or access denied"}), 404

    meeting    = MeetingModel.find_by_id(current_app.db, meeting_id)
    transcript = TranscriptModel.find_by_meeting(current_app.db, meeting_id)
    analysis   = AnalysisModel.find_by_meeting(current_app.db, meeting_id)

    if not meeting:
        return jsonify({"error": "Meeting not found"}), 404

    styles = _build_styles()
    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2.5*cm, bottomMargin=2.5*cm,
    )

    story = []
    title = meeting.get("ai_title") or meeting.get("title", "Meeting Report")

    # ── Cover block ────────────────────────────────────────────────────────────
    story.append(Paragraph(title, styles["title"]))
    story.append(Paragraph(
        f"Generated by AI Meeting Analyzer &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"{_fmt_time(meeting.get('created_at'))}",
        styles["subtitle"],
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE))
    story.append(Spacer(1, 12))

    # ── Metadata table ─────────────────────────────────────────────────────────
    sentiment = (analysis or {}).get("sentiment_overall", {})
    sent_label = sentiment.get("label", "N/A") or "N/A"

    meta_data = [
        ["Duration",     _fmt_duration(meeting.get("duration_seconds", 0))],
        ["Language",     (meeting.get("language") or "N/A").upper()],
        ["File",         meeting.get("file_name", "N/A")],
        ["Participants", str(len(meeting.get("participants", []))) or "N/A"],
        ["Sentiment",    sent_label.capitalize()],
        ["Status",       meeting.get("status", "N/A").capitalize()],
    ]
    meta_table = Table(meta_data, colWidths=[4.5*cm, 11*cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 10),
        ("TEXTCOLOR",   (0, 0), (0, -1), ACCENT_GRAY),
        ("TEXTCOLOR",   (1, 0), (1, -1), BRAND_DARK),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_GRAY, colors.white]),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 20))

    # ── AI Summary ─────────────────────────────────────────────────────────────
    if analysis and analysis.get("summary"):
        story.append(Paragraph("AI Summary", styles["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY))
        story.append(Spacer(1, 6))
        story.append(Paragraph(analysis["summary"], styles["body"]))
        story.append(Spacer(1, 12))

    # ── Key Points ─────────────────────────────────────────────────────────────
    if analysis and analysis.get("key_points"):
        story.append(Paragraph("Key Discussion Points", styles["h2"]))
        for point in analysis["key_points"]:
            story.append(Paragraph(f"• {point}", styles["bullet"]))
        story.append(Spacer(1, 12))

    # ── Action Items ───────────────────────────────────────────────────────────
    if analysis and analysis.get("action_items"):
        story.append(Paragraph("Action Items", styles["h2"]))
        ai_data = [["#", "Action", "Assignee", "Priority"]]
        for i, item in enumerate(analysis["action_items"], 1):
            ai_data.append([
                str(i),
                item.get("text", ""),
                item.get("assignee", "—"),
                item.get("priority", "—").capitalize(),
            ])
        ai_table = Table(ai_data, colWidths=[1*cm, 10*cm, 3.5*cm, 2.5*cm])
        ai_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), BRAND_BLUE),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
            ("TOPPADDING",  (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("GRID",        (0, 0), (-1, -1), 0.25, LIGHT_GRAY),
        ]))
        story.append(ai_table)
        story.append(Spacer(1, 12))

    # ── Decisions ─────────────────────────────────────────────────────────────
    if analysis and analysis.get("decisions"):
        story.append(Paragraph("Key Decisions", styles["h2"]))
        for dec in analysis["decisions"]:
            story.append(Paragraph(f"✓  {dec.get('text', dec)}", styles["bullet"]))
        story.append(Spacer(1, 12))

    # ── Sentiment overview ─────────────────────────────────────────────────────
    if sentiment and sentiment.get("label"):
        story.append(Paragraph("Sentiment Analysis", styles["h2"]))
        sent_data = [
            ["Overall",  sent_label.capitalize(),
             f"{round(float(sentiment.get('score', 0)) * 100)}% confidence"],
            ["Positive", f"{round(float(sentiment.get('positive', 0)) * 100)}%", ""],
            ["Negative", f"{round(float(sentiment.get('negative', 0)) * 100)}%", ""],
            ["Neutral",  f"{round(float(sentiment.get('neutral', 0)) * 100)}%",  ""],
        ]
        s_table = Table(sent_data, colWidths=[4*cm, 4*cm, 9*cm])
        s_table.setStyle(TableStyle([
            ("FONTNAME",  (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",  (0, 0), (-1, -1), 10),
            ("TEXTCOLOR", (0, 0), (0, -1), ACCENT_GRAY),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_GRAY, colors.white]),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ]))
        story.append(s_table)
        story.append(Spacer(1, 12))

    # ── Keywords ───────────────────────────────────────────────────────────────
    if analysis and analysis.get("keywords"):
        story.append(Paragraph("Top Keywords", styles["h2"]))
        kw_str = "  •  ".join(
            kw["word"] if isinstance(kw, dict) else str(kw)
            for kw in analysis["keywords"][:20]
        )
        story.append(Paragraph(kw_str, styles["tag"]))
        story.append(Spacer(1, 12))

    # ── Full Transcript ────────────────────────────────────────────────────────
    if transcript and transcript.get("segments"):
        story.append(Paragraph("Full Transcript", styles["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY))
        story.append(Spacer(1, 8))

        current_speaker = None
        for seg in transcript["segments"]:
            speaker = seg.get("speaker", "Unknown")
            text    = seg.get("text", "").strip()
            start   = seg.get("start", 0)
            m, s    = divmod(int(start), 60)
            ts      = f"[{m:02d}:{s:02d}]"

            # New speaker label
            if speaker != current_speaker:
                current_speaker = speaker
                story.append(Paragraph(f"{speaker} {ts}", styles["speaker"]))

            story.append(Paragraph(text, styles["segment"]))

    elif transcript and transcript.get("full_text"):
        story.append(Paragraph("Full Transcript", styles["h2"]))
        story.append(Paragraph(transcript["full_text"], styles["body"]))

    # ── Footer ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"AI Meeting Analyzer  |  Exported on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        styles["footer"],
    ))

    # ── Build PDF ──────────────────────────────────────────────────────────────
    try:
        doc.build(story)
    except Exception as e:
        logger.error(f"PDF build failed for meeting {meeting_id}: {e}")
        return jsonify({"error": "PDF generation failed"}), 500

    buffer.seek(0)
    safe_title = "".join(c for c in title if c.isalnum() or c in " _-")[:50]
    filename   = f"{safe_title.replace(' ', '_')}_report.pdf"

    return send_file(
        buffer,
        mimetype="application/pdf",
        as_attachment=True,
        download_name=filename,
    )


# ══════════════════════════════════════════════════════════════════════════════
# TRANSCRIPT-ONLY PDF
# ══════════════════════════════════════════════════════════════════════════════

def export_transcript_pdf(meeting_id: str):
    """
    GET /api/export/<meeting_id>/transcript
    Generates a transcript-only PDF (lighter, faster).
    """
    if not verify_meeting_ownership(meeting_id):
        return jsonify({"error": "Not found or access denied"}), 404

    meeting    = MeetingModel.find_by_id(current_app.db, meeting_id)
    transcript = TranscriptModel.find_by_meeting(current_app.db, meeting_id)

    if not transcript:
        return jsonify({"error": "Transcript not available"}), 404

    styles = _build_styles()
    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(buffer, pagesize=A4,
                               leftMargin=2*cm, rightMargin=2*cm,
                               topMargin=2.5*cm, bottomMargin=2.5*cm)
    story  = []
    title  = meeting.get("ai_title") or meeting.get("title", "Transcript")

    story.append(Paragraph(title, styles["title"]))
    story.append(Paragraph("Meeting Transcript", styles["subtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE))
    story.append(Spacer(1, 12))

    if transcript.get("segments"):
        current_speaker = None
        for seg in transcript["segments"]:
            speaker = seg.get("speaker", "Unknown")
            text    = seg.get("text", "").strip()
            start   = seg.get("start", 0)
            m, s    = divmod(int(start), 60)
            if speaker != current_speaker:
                current_speaker = speaker
                story.append(Paragraph(f"{speaker}  [{m:02d}:{s:02d}]", styles["speaker"]))
            story.append(Paragraph(text, styles["segment"]))
    else:
        story.append(Paragraph(transcript.get("full_text", ""), styles["body"]))

    doc.build(story)
    buffer.seek(0)
    safe  = "".join(c for c in title if c.isalnum() or c in " _-")[:50]
    fname = f"{safe.replace(' ', '_')}_transcript.pdf"

    return send_file(buffer, mimetype="application/pdf",
                     as_attachment=True, download_name=fname)
